### ISSUE TITLE
Comments are not being added

### ISSUE THREAD

**Issue by Oxxyg33n** [fpicalausa/remove-stale-branches#14]
Hello! Tried your github action, it seems like it marks the branches as stale, but it doesn't leave any comment, is there a problem in my configuration or some permissions are missing? In GA logs there are no errors.

Configuration:

```
name: Remove stale branches
on:
  schedule:
    - cron: "0 0 * * *" # Everday at midnight
  workflow_dispatch:

jobs:
  remove-stale-branches:
    name: Remove Stale Branches
    runs-on: ubuntu-latest
    steps:
      - uses: fpicalausa/remove-stale-branches@v1.6.0
        with:
          dry-run: "false" # Check out the console output before setting this to false
          exempt-authors-regex: "^dependabot"
          exempt-protected-branches: "true"
          exempt-branches-regex: "^(master|main)$"
          days-before-branch-stale: "90"
          days-before-branch-delete: "7"
          operations-per-run: "100"
          ignore-unknown-authors: "true"
          default-recipient: "Oxxyg33n"
```
