### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by defyjoy** [fpicalausa/remove-stale-branches#25]
HI I am using the reusable templates and I am getting this error - 

![image](https://github.com/user-attachments/assets/460b7346-6b11-4658-a15d-c3e8e66e5f15)

```
on:
  workflow_call:
    inputs:
      exempt-branches-regex:
        description: Exempted branches from the deletion
        required: false
        type: string
        default: '^(main|master)$'
jobs: 
  cron:
    runs-on: ubuntu-latest
    name: Stale branches
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Stale Branches Identification And Removal
        uses: fpicalausa/remove-stale-branches@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: false # Check out the console output before setting this to false
          # exempt-organization: "acme-inc"
          # exempt-authors-regex: "^dependabot"
          days-before-branch-stale: 60
          days-before-branch-delete: 7
          ignore-unknown-authors: true
          default-recipient: joydeep.roychowdhury@skf.com
          exempt-branches-regex: ${{ inputs.exempt-branches-regex}}
          operations-per-run: 100
          ignore-branches-with-open-prs: true
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
```

And this is how its called now - 
```
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Everday at midnight

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  Cron:
    secrets: inherit
    uses: SKF-Internal/darwin-github-actions-templates/.github/workflows/delete-stale-branches.yaml@main
```

Any idea what is the issue ? 

## UPDATE

I have added `secrets: inherit` parameter in the cron job

**Comment by fpicalausa** [comment]
@defyjoy it looks like the action may not have the right permissions to run the GQL query.

What it needs is access (read and write) to the contents in the repo, including commenting on commits. Can you confirm which scopes are in available for your GITHUB_TOKEN?

**Comment by defyjoy** [comment]
I believe this is what the scopes are I have already mentioned above ? 

```
permissions:
  id-token: write
  contents: write
  packages: write
```
