### ISSUE TITLE
exempt-protected-branches input doesn't work

### ISSUE THREAD

**Issue by davidkominekhypixelstudios** [fpicalausa/remove-stale-branches#35]
Following workflow has `exempt-protected-branches: true` which should exclude protected branches but it doesn't work and still flags protected branches as stale.

```
name: Stale Branch Cleanup

on:
    workflow_dispatch:
        inputs:
            operations:
                type: number
                required: false
                default: 50
    schedule:
        - cron: "0 0 * * *" # Everday at midnight

jobs:
    remove-stale-branches:
        name: Remove Stale Branches
        runs-on: ubuntu-latest
        steps:
            -   uses: fpicalausa/remove-stale-branches@v2.1.2
                with:
                    dry-run: false # Check out the console output before setting this to false
                    exempt-protected-branches: true
                    days-before-branch-stale: 30
                    stale-branch-message: |
                        placeholder message
                    days-before-branch-delete: 30
                    operations-per-run: "${{ github.event.inputs.operations || 50 }}"
                    ignore-branches-with-open-prs: true
                    ignore-unknown-authors: true
                    default-recipient: placeholder_recipient
```
