### ISSUE TITLE
Why it is not scanning all the branches in the real run mode?

### ISSUE THREAD

**Issue by lal2hc** [fpicalausa/remove-stale-branches#38]
I am using the latest version fpicalausa/remove-stale-branches@v2.2.0 with below options

```
Run fpicalausa/remove-stale-branches@v2.2.0
  with:
    dry-run: false
    github-token: ***
    operations-per-run: 5000
    exempt-protected-branches: true
    exempt-branches-regex: ^(?!.*stale-branch).+$
    ignore-branches-with-open-prs: true
    days-before-branch-stale: 10
    days-before-branch-delete: 7
    stale-branch-message: @{author} Your branch hasn't been updated in the last {daysBeforeBranchStale} days and is marked as stale. It will be removed in {daysBeforeBranchDelete} days. If you want to keep this branch around, delete this comment or add new commits to this branch.
    ignore-unknown-authors: false
```

> With dry-run=true
Summary:  **380 scanned**, ✅ 2 skipped, ✏ 0 marked stale, 😐 10 kept stale, ❌ 368 removed

> With dry-run=false
Summary:  **200 scanned**, ✅ 1 skipped, ✏ 0 marked stale, 😐 10 kept stale, ❌ 189 removed

Do you know why it doesn't scan all branches in actual run mode?
